version: "3"
services:
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

volumes:
  mongodata: